### ISSUE TITLE
Issue with logging in: Sorry the credentials you are using are invalid

### ISSUE THREAD

**Issue by sorenvdb** [neutrino-steak/UE4LinuxLauncher#1]
Hi, trying to log in from Quebec, Canada using an EpicGames account, and I get the message in the title after clicking Login. It may also be a permission error since the internet where I work is restricted. 

I'm also having issues compiling it (I was trying to debug it). An exception gets thrown in the version I compiled saying 

```
Exception in thread "main" java.awt.IllegalComponentStateException: contentPane cannot be set to null.
	at java.desktop/javax.swing.JRootPane.setContentPane(JRootPane.java:598)
	at java.desktop/javax.swing.JFrame.setContentPane(JFrame.java:679)
	at launcher.LoginForm.<init>(LoginForm.java:22)
	at launcher.Main.checkIfLoggedIn(Main.java:61)
	at launcher.Main.<init>(Main.java:55)
	at launcher.Main.main(Main.java:19)

```
Are there any dependencies or anything I need to install? 

Thanks.

**Comment by neutrino-steak** [comment]
The login issue is due to Epic changing their auth flow again, and would require me to implement some changes in the project to get the login process working again.

I won't be able to start on a fix for another week or so, as I am currently recovering from a medical procedure to repair some torn cartilage in my wrist. I would suggest checking out a different cross-platform launcher project: [nmrugg/UE4Launcher](https://github.com/nmrugg/UE4Launcher), written with NodeJS. The creator has implemented changes for the current auth flow, as well as some other useful features. I highly recommend giving it a try.
